name: cliq
description: "CLIq: Portable and secure SSH and SFTP client."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cliq_terminal:
    path: packages/cliq_terminal
  cliq_ui:
    path: packages/cliq_ui
  lucide_flutter: ^0.542.0
  go_router: ^16.0.0
  flutter_hooks: ^0.21.2
  shared_preferences: ^2.5.3
  hooks_riverpod: ^2.6.1
  riverpod: ^2.6.1
  logging: ^1.3.0
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  drift_dev: ^2.28.1
  build_runner: ^2.7.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
